# ===== Supabase PostgreSQL via Session Pooler =====
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qhrszjbdeipydpagoyii
spring.datasource.password=RebuyProject12

# JPA / Hibernate
#Hibernate = the system that converts Java objects to database tables.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true