name: CI/CD Rebuy Project

on:
  push:
    branches:
      - main
      - mainCICD
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to mvnw
        run: chmod +x Rebuy-backend-with-tests/backend/mvnw

      - name: Run backend tests
        run: cd Rebuy-backend-with-tests/backend && ./mvnw test
